### ISSUE TITLE
Outdated install instructions?

### ISSUE THREAD

**Issue by jacobwhall** [dracula/slack#10]
I'm using Slack for Linux version 4.13.0

The install instructions for this repository did not work for me. Slack put the copy-pasted color codes in a code block, but did not give me the option to install this theme.

The [Change your Slack theme](https://slack.com/help/articles/205166337-Change-your-Slack-theme) article in the Slack Help Center says that custom theme colors should be installed by navigating to Preferences > Themes > Colors and defining your own custom colors. Pasting the color codes from this repo into the text box worked for me.

May I submit a pull request that changes the install instructions to match those in the Slack Help Center?

**Comment by jacobwhall** [comment]
Right after submitting this, I found #7, which attempts to fix the issue I'm describing. Forcing the color codes to not be in a code block makes Slack recognize them as a potential "sidebar theme." I don't know which method is easier to articulate in the install instructions, but I still think a change should be made.

**Comment by jacobwhall** [comment]
In PR #6 @aws5295 describes the text box in Preferences > Themes as read-only, so I guess Slack has since fixed that behavior. The text box is definitely editable now, and the theme changes in real-time as I edit it.

**Comment by KyleJamesWalker** [comment]
This is fixed in #8

**Comment by taka0o** [comment]
Hello @jacobwhall, thank you for reporting this issue. I've just updated the installation instructions and closed the PR you were mentionning as I'm the new maintainer for this repo. Let us know if there's anything else you need to report.
