### ISSUE TITLE
Slack 4.35.126 rejects the theme string

### ISSUE THREAD

**Issue by jonathaneagle** [dracula/slack#17]
When entering the string into the "theme string" field, the error message "Invalid theme string" is displayed.

![image](https://github.com/dracula/slack/assets/8041767/2b874215-bd2e-4094-8e45-866113ef7cf3)

This was using Slack Snap 4.35.126 64-bit

**Comment by dimitarmanov** [comment]
@jonathaneagle, I had the same problem. Make sure the last color doesn't have ";"

It should look like this
#282A36,#44475A,#44475A,#8BE9FD,#6272A4,#FFFFFF,#50FA7B,#FF5555,#44475A,#FFFFFF

**Comment by jonathaneagle** [comment]
Oh no way, that worked. Thanks! 
Any chance the instructions on the webpage could get updated then for future visitors?

**Comment by quagliato** [comment]
@D-u-c-k-s-e-l's PR https://github.com/dracula/slack/pull/18 fixed the issue. Thanks! :)
