### ISSUE TITLE
Should text color be #F8F8F2?

### ISSUE THREAD

**Issue by teddybradford** [dracula/slack#3]
Should the text color be #F8F8F2 instead of #FFFFFF based on the color scheme listed in dracula/dracula-theme?

**Comment by CGS-Jack-Bashford** [comment]
So, do you want essentially a very, very, very light grey instead of plain white? I actually think that looks quite nice...it's set up in my Slack (I'm using Dracula theme)

**Comment by JimmyMultani** [comment]
Hey @teddybradford, you're right. This should be fixed shortly once #8 is merged in.

**Comment by quagliato** [comment]
Hey! #8 PR was merged a few minutes ago, so I'll close this issue. Thanks!
