### ISSUE TITLE
Slack custom themes require 9 values?

### ISSUE THREAD

**Issue by shayhurley** [dracula/slack#9]
It looks like slack now uses 9 values for custom themes but the dracula theme only includes 8?:

![image](https://user-images.githubusercontent.com/8726/100595244-92b8ef80-32f2-11eb-9d7c-c63b271f2cfa.png)

**Comment by jacobwhall** [comment]
#8 fixes this. I recommend grabbing the codes from that PR until the maintainer merges it.

**Comment by quagliato** [comment]
#8 PR was merged a few minutes ago, so I'll close this issue. :) Thanks!
